### ISSUE TITLE
hosts files have errors

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#18]
We had some anomalies in production, and we found out that production was hitting dev services. After some investigations, we realized that the hosts file was wrong.

I fixed one entry on the monarch-app-prod in order to fix production, but it might be worth checking if there are any other typos.

The one I fixed was:
10.95.40.133	scigraph-ontology.monarchinitiative.org scigraph-ontology

It should be 10.95.40.131.

**Comment by jnguyenx** [comment]
And another comment:

It was really confusing for us to debug that. Our first move was to run the stack locally in order to debug, but we couldn't expose the bug since the urls were resolving to the right servers.

**Comment by vanmatre** [comment]
Sorry about the typo - Fixed in all hosts files.

I will be bringing up a DNS server today to allow internal and external addresses to resolve correctly based on where the resolver is.

This will help remove issues with name resolution.

--Ethan


Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________
