### ISSUE TITLE
monarch-solr-prod needs more diskspace

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#37]
We'll copy data over from monarch-solr-dev. Ideally can you extend the disk space to 1TB on production to match the dev specs?

**Comment by vanmatre** [comment]
Let me know when the copy is complete and I'll rebuild the prod VM

**Comment by jnguyenx** [comment]
Can it be done with a minimal downtown and without losing our data?

**Comment by vanmatre** [comment]
Not so easy. We could bring up an other VM that you could copy the data over to the switch addresses....



Ethan VanMatre
Informatics Research Analyst
Institute on Development and Disability
Oregon Health & Science University
CSLU - GH40
3181 SW Sam Jackson Park Rd
Portland, OR 97239
(503) 346-3764
vanmatre@ohsu.edu
________________________________

**Comment by jnguyenx** [comment]
I remembered that @kltm was increasing disk space with minimal downtime.
Seth, if I recall correctly, do you have any tips?

**Comment by vanmatre** [comment]
The VM use ext4 internally (not lvm) which makes it a bit harder. Tips would be useful - I can try a few tests in cating container files together and then extending the disk image - swap is the second partition on the disk. but We have a /boot do root is the 3rd partition and might extend well.

**Comment by vanmatre** [comment]
I'll think about adding a NFS disk from the base metal to the VM. We can get some throughput metrics and if good then we will have a much larger way for app space.

**Comment by kltm** [comment]
Sorry, just getting back into things here.

Uhhh...
You can technically get a bigger partition (fdisk) and then grow with resize2fs, but it is a bit of mucking around in the weeds (and assumes that you have more space to grow into). If the VMs are disposable/recreatable, wouldn't it just be easier to great the new enlarged machine and just flip to it (as https://github.com/monarch-initiative/monarch-devops/issues/37#issuecomment-210678077)?

Again, as @vanmatre mentioned, it might be easier to factor the data out of the equation onto an NFS that could be controlled separately. The downside being, well, NFS, which might we less than ideal considering the amount of i/o and sizes you're dealing with. We've done things with shared block-level storage in the past, but was not worth the overhead in the end; however, in this case (same real hardware), it might be fine.

If somebody could fill me in on exactly the problem here, I might be able to give more specific thoughts (maybe @jnguyenx in meatspace).

**Comment by jnguyenx** [comment]
I had a quick chat with Seth, what he wrote in his comment was based on the
fact that we needed to do that without downtime.

Increasing disk space with data preservation should be doable with a
reasonable downtime. If I recall correctly we're running on KVM right? That
may help
http://serverfault.com/questions/324281/how-do-you-increase-a-kvm-guests-disk-space

It'd be wise to test that command on a test VM :-)

Let me know if this is reasonable for you Ethan.

**Comment by vanmatre** [comment]
I agree that testing is required. The partitions are not LVM so the resize becomes a bit more interesting... I've done it before but there is a lot to go wrong. In any case I will copy the container file (for a true backup) before trying it on the "actual" VM.\
It will take a day or few to get the time and to do the testing. 

-_Ethan

**Comment by vanmatre** [comment]
OK - got some time to creat NFS mounts on each of the VM.... Let's see if this takes care of the space problem.

Preamble: Each VM run on some base hardware (VM (e.g. monarch1-1) runs on hardward monarch1). The base hardware on monarch[1-4] has 20 or so TB of storage that is under utilized. Monarch5 has much less disk but follows the same scheme.

So I created a directory on each hardware server that has access to the full free space on the base hardware. The directory name is /disk/vmpartition/data and this directory is exported via NFS.

On each VM I have mounted the data directory served by its base hardware (monarchN:/disk/vmpartition/data) onto a local (to the VM) mount point /mnt/data. 

/mnt/data is shared by all of the VM on a specific base hardware server.

Because the VM is actually running onthe base hardware that it is mounting the directory from we never actually put any NFS traffic on the "network". This should give us good performance. And I will look at tuning the NFS parameters as we encounter problems or metrics indicate.

Give it a try and let me know if it meet the need for more disk space.

Of course you should come up with a scheme to keep the data space used by one VM form being walked on by another VM. Something like: /mnt/data/<vm-name>.<app-name>/<your data>

--Ethan

**Comment by vanmatre** [comment]
evm@monarch-solr-prod:~$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
udev                              16G  4.0K   16G   1% /dev
tmpfs                            3.2G  432K  3.2G   1% /run
/dev/vda3                        489G  289G  176G  63% /
none                             4.0K     0  4.0K   0% /sys/fs/cgroup
none                             5.0M     0  5.0M   0% /run/lock
none                              16G     0   16G   0% /run/shm
none                             100M     0  100M   0% /run/user
/dev/vda1                        232M   70M  146M  33% /boot
monarch2:/disk/vmpartition/data   22T  3.1T   18T  15% /mnt/data

**Comment by kltm** [comment]
Is there any way to benchmark NFS versus non-NFS i/o performance here? There are enough layers here, I could see it really grinding down (https://github.com/monarch-initiative/monarch-devops/issues/37#issuecomment-212151530).

**Comment by vanmatre** [comment]
there are falsehoods, lies, statistics and benchmarks.....
But a few quick single stream rsyncs shows that we can expect NFS traffic to equal or exceed local traffic. At least for single copies.

I created a single 8 GB file and rsynced it to a new location on the base hardware disks. This is to give us a baseline. The average transfer rate was 188 MB/s and took 45 seconds. The range was from a low of 120 MB/s to 214 MB/s. (Lots of free cpu cycles and direct access to the disk controllers)

Then I rsynced the same file from the VM to the NFS "disk" (write from VM) - there was a 108 MB/s average taking 1m 19s to copy the file. The range was from 90 MB/s to 129 MB/s.

I rsynced the file from the NFS disk to the VM disk (read from NFS) - there was a 132 MN/s average and it took 1m 5s to copy the file. The range was from 100 MB/s to 159 MB/s.

lastly I rsynced the file within the VM (VM to VM copy) with an average transfer rate of 101 MB/s and taking 1m 25 s to copy. The range was 77 MB/s to 120 MB/s. This was the slowest.

Of course the system load is dynamic so we will get a significant range of transfer speeds. The transfer on the base hardware is the fastest as we expect. Closer to the disk controllers and all the CPU and cache you can use.

The VM to VM copy was the slowest which also should be expected. The copy goes from the VM container file to the VM container file which is the bottle neck and highly dependent on caching.

Copy to or from NFS is actually a copy from the VM container file to/from a file on the base system. The overhead of the network stack is less than the overhead caused by the contention  in VM to VM operations. (or so it appears)

Of course this is single stream and at some point the NFS daemons will be maxed out and would need to be increased to handle the increased IOPS along with other tuning. Doing straight reads or writes to a program are another kettle of fish.

**Comment by jnguyenx** [comment]
Using it live since today, let's see how it performs.

**Comment by jnguyenx** [comment]
I'm reopening this as I think that NFS is a working solution for some of our needs only.

It suits well the jenkins CI for generating large files (although performance could be better). However for production I don't feel comfortable to have data sitting on a shared NFS. For example for solr, the data folders sit next to each other:

> monarch-solr-dev:~$ ll  /mnt/data/
> total 24
> drwxrwxrwx 4 monarch monarch 4096 Jul  8 14:08 ./
> drwxr-xr-x 3 root    root    4096 Apr 27 13:40 ../
> -rw-r--r-- 1 root    root     351 Apr 27 13:22 README
> drwxr-xr-x 6 jetty   jetty   4096 Jun 22 16:20 solr-server-dev/
> drwxr-xr-x 6 sshd    ntp     4096 Jun 22 16:20 solr-server-prod/

If it's possible, I'd still like to try out the route where we'll be able to expand disk sizes with the cost of a VM reboot.

**Comment by kltm** [comment]
Those groups/permissions are worrying. It looks like the users on the different client machines are not in sync (or using a centralized shared user set). That could cause all sorts of unforeseen consequences with locks and the like.
NFS may not be the best solution here (also thinking about performance and NFS being the creature that it is, often not paired with databases).

**Comment by vanmatre** [comment]
The VM is currently using 3.9 TB on the NFS partition. What size is needed. As with Scigraph-data-prod I can create a new VM and we can prep it to take over production. Using LVM which can allow for disk expansion.

evm@monarch-solr-prod:~$ df -h
Filesystem                       Size  Used Avail Use% Mounted on
udev                              16G  4.0K   16G   1% /dev
tmpfs                            3.2G  432K  3.2G   1% /run
/dev/vda3                        489G   56G  409G  12% /
none                             4.0K     0  4.0K   0% /sys/fs/cgroup
none                             5.0M     0  5.0M   0% /run/lock
none                              16G     0   16G   0% /run/shm
none                             100M     0  100M   0% /run/user
/dev/vda1                        232M   70M  146M  33% /boot
monarch2:/disk/vmpartition/data   22T  3.9T   17T  19% /mnt/data

**Comment by jnguyenx** [comment]
Done on new monarch-solr6 VMs.
