### ISSUE TITLE
subdomain clean up

### ISSUE THREAD

**Issue by jnguyenx** [monarch-initiative/monarch-devops#6]
Are there any sub-domains which are not pointing to OHSU servers? I guess that there are still some pointing to UCSD.

**Comment by vanmatre** [comment]
owlsim forward has had the trailing / removed

beta and solr-dev forwards created

scigraph-ontology-dev and scigraph-data-dev are existing A records. 

N.B. I have been pointing forwards and CNAMES to NNN.monarchinitiative.org rather than to the ohsu names (to avoid ohsu DNS oddities between internal and external addresses). I can revisit this if we cannot make it work.
Also, If need be I can spin up a DNS server to do views to resolve internal and external addresses. More hoops but I have done it before here at ohsu.

All existing addresses/cnames were put into godaddy's dns and those requested were changed over to the ohsu address space. The others were left over and have now been removed.

In total 11 A records and 7 CNAME records pointing to "outside" servers removed.
data
datagraph
mail
neville
persei
poole
postgres
prod
services
sirius
stage
---
beta
beta-log
create
downloads
kato
stage-monarch
stage-owlsim

**Comment by jnguyenx** [comment]
Thanks!
